name: Palindrome Check

on: [push, pull_request]

jobs:
  palindrome_job:
    name: Check if string is a palindrome
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Run Python script
      run: |
        python - <<EOF
        def isPalindrome(s):
            return s == s[::-1]

        s = "malayalam"
        ans = isPalindrome(s)
        if ans:
            print("Yes")
        else:
            print("No")
        EOF
